// utils/phoneValidation.ts

import { Country } from "react-phone-number-input";

interface CountryPhoneRule {
  minLength: number;
  maxLength: number;
  exactLength?: number;
  pattern?: RegExp;
}

export const phoneValidationRules: Record<Country, CountryPhoneRule> = {
  IN: { minLength: 10, maxLength: 10, exactLength: 10 },
  US: { minLength: 10, maxLength: 10 },
  GB: { minLength: 9, maxLength: 11 },
  CA: { minLength: 10, maxLength: 10 },
  AU: { minLength: 9, maxLength: 10 },
  DE: { minLength: 10, maxLength: 11 },
  FR: { minLength: 9, maxLength: 10 },
  AC: { minLength: 1, maxLength: 3 },
  AD: { minLength: 8, maxLength: 8 },
  AE: { minLength: 9, maxLength: 9 },
  AF: { minLength: 9, maxLength: 9 },
  AG: { minLength: 7, maxLength: 7 },
  AI: { minLength: 7, maxLength: 7 },
  AL: { minLength: 9, maxLength: 9 },
  AM: { minLength: 8, maxLength: 8 },
  AO: { minLength: 9, maxLength: 9 },
  AR: { minLength: 10, maxLength: 10 },
  AS: { minLength: 7, maxLength: 7 },
  AT: { minLength: 10, maxLength: 13 },
  AW: { minLength: 7, maxLength: 7 },
  AX: { minLength: 6, maxLength: 15 },
  AZ: { minLength: 9, maxLength: 9 },
  BA: { minLength: 8, maxLength: 8 },
  BB: { minLength: 7, maxLength: 7 },
  BD: { minLength: 10, maxLength: 10 },
  BE: { minLength: 9, maxLength: 9 },
  BF: { minLength: 8, maxLength: 8 },
  BG: { minLength: 9, maxLength: 9 },
  BH: { minLength: 8, maxLength: 8 },
  BI: { minLength: 8, maxLength: 8 },
  BJ: { minLength: 8, maxLength: 8 },
  BL: { minLength: 9, maxLength: 9 },
  BM: { minLength: 7, maxLength: 7 },
  BN: { minLength: 7, maxLength: 7 },
  BO: { minLength: 8, maxLength: 8 },
  BQ: { minLength: 7, maxLength: 7 },
  BR: { minLength: 10, maxLength: 11 },
  BS: { minLength: 7, maxLength: 7 },
  BT: { minLength: 8, maxLength: 8 },
  BW: { minLength: 8, maxLength: 8 },
  BY: { minLength: 9, maxLength: 9 },
  BZ: { minLength: 7, maxLength: 7 },
  CC: { minLength: 10, maxLength: 10 },
  CD: { minLength: 9, maxLength: 9 },
  CF: { minLength: 8, maxLength: 8 },
  CG: { minLength: 9, maxLength: 9 },
  CH: { minLength: 9, maxLength: 9 },
  CI: { minLength: 10, maxLength: 10 },
  CK: { minLength: 5, maxLength: 5 },
  CL: { minLength: 8, maxLength: 9 },
  CM: { minLength: 9, maxLength: 9 },
  CN: { minLength: 11, maxLength: 11 },
  CO: { minLength: 10, maxLength: 10 },
  CR: { minLength: 8, maxLength: 8 },
  CU: { minLength: 8, maxLength: 8 },
  CV: { minLength: 7, maxLength: 7 },
  CW: { minLength: 8, maxLength: 8 },
  CX: { minLength: 10, maxLength: 10 },
  CY: { minLength: 8, maxLength: 8 },
  CZ: { minLength: 9, maxLength: 9 },
  DJ: { minLength: 8, maxLength: 8 },
  DK: { minLength: 8, maxLength: 8 },
  DM: { minLength: 7, maxLength: 7 },
  DO: { minLength: 10, maxLength: 10 },
  DZ: { minLength: 9, maxLength: 9 },
  EC: { minLength: 9, maxLength: 9 },
  EE: { minLength: 8, maxLength: 8 },
  EG: { minLength: 10, maxLength: 10 },
  EH: { minLength: 9, maxLength: 9 },
  ER: { minLength: 7, maxLength: 7 },
  ES: { minLength: 9, maxLength: 9 },
  ET: { minLength: 9, maxLength: 9 },
  FI: { minLength: 9, maxLength: 12 },
  FJ: { minLength: 7, maxLength: 7 },
  FK: { minLength: 5, maxLength: 5 },
  FM: { minLength: 7, maxLength: 7 },
  FO: { minLength: 6, maxLength: 6 },
  GA: { minLength: 7, maxLength: 7 },
  GD: { minLength: 7, maxLength: 7 },
  GE: { minLength: 9, maxLength: 9 },
  GF: { minLength: 10, maxLength: 10 },
  GG: { minLength: 10, maxLength: 10 },
  GH: { minLength: 10, maxLength: 10 },
  GI: { minLength: 8, maxLength: 8 },
  GL: { minLength: 6, maxLength: 6 },
  GM: { minLength: 8, maxLength: 8 },
  GN: { minLength: 8, maxLength: 8 },
  GP: { minLength: 10, maxLength: 10 },
  GQ: { minLength: 9, maxLength: 9 },
  GR: { minLength: 10, maxLength: 10 },
  GT: { minLength: 8, maxLength: 8 },
  GU: { minLength: 7, maxLength: 7 },
  GW: { minLength: 7, maxLength: 7 },
  GY: { minLength: 7, maxLength: 7 },
  HK: { minLength: 8, maxLength: 8 },
  HN: { minLength: 8, maxLength: 8 },
  HR: { minLength: 9, maxLength: 9 },
  HT: { minLength: 8, maxLength: 8 },
  HU: { minLength: 9, maxLength: 9 },
  ID: { minLength: 10, maxLength: 12 },
  IE: { minLength: 8, maxLength: 9 },
  IL: { minLength: 9, maxLength: 9 },
  IM: { minLength: 10, maxLength: 10 },
  IO: { minLength: 7, maxLength: 7 },
  IQ: { minLength: 10, maxLength: 10 },
  IR: { minLength: 10, maxLength: 10 },
  IS: { minLength: 7, maxLength: 7 },
  IT: { minLength: 9, maxLength: 11 },
  JE: { minLength: 10, maxLength: 10 },
  JM: { minLength: 7, maxLength: 7 },
  JO: { minLength: 9, maxLength: 9 },
  JP: { minLength: 10, maxLength: 11 },
  KE: { minLength: 10, maxLength: 10 },
  KG: { minLength: 9, maxLength: 9 },
  KH: { minLength: 9, maxLength: 9 },
  KI: { minLength: 8, maxLength: 8 },
  KM: { minLength: 7, maxLength: 7 },
  KN: { minLength: 7, maxLength: 7 },
  KP: { minLength: 10, maxLength: 10 },
  KR: { minLength: 10, maxLength: 11 },
  KW: { minLength: 8, maxLength: 8 },
  KY: { minLength: 10, maxLength: 10 },
  KZ: { minLength: 10, maxLength: 10 },
  LA: { minLength: 8, maxLength: 8 },
  LB: { minLength: 8, maxLength: 8 },
  LC: { minLength: 7, maxLength: 7 },
  LI: { minLength: 9, maxLength: 9 },
  LK: { minLength: 9, maxLength: 9 },
  LR: { minLength: 8, maxLength: 8 },
  LS: { minLength: 8, maxLength: 8 },
  LT: { minLength: 8, maxLength: 8 },
  LU: { minLength: 9, maxLength: 9 },
  LV: { minLength: 8, maxLength: 8 },
  LY: { minLength: 9, maxLength: 9 },
  MA: { minLength: 9, maxLength: 10 },
  MC: { minLength: 8, maxLength: 8 },
  MD: { minLength: 8, maxLength: 8 },
  ME: { minLength: 9, maxLength: 9 },
  MF: { minLength: 10, maxLength: 10 },
  MG: { minLength: 9, maxLength: 9 },
  MH: { minLength: 7, maxLength: 7 },
  MK: { minLength: 8, maxLength: 8 },
  ML: { minLength: 8, maxLength: 8 },
  MM: { minLength: 9, maxLength: 9 },
  MN: { minLength: 8, maxLength: 8 },
  MO: { minLength: 8, maxLength: 8 },
  MP: { minLength: 7, maxLength: 7 },
  MQ: { minLength: 10, maxLength: 10 },
  MR: { minLength: 8, maxLength: 8 },
  MS: { minLength: 7, maxLength: 7 },
  MT: { minLength: 8, maxLength: 8 },
  MU: { minLength: 8, maxLength: 8 },
  MV: { minLength: 7, maxLength: 7 },
  MW: { minLength: 8, maxLength: 8 },
  MX: { minLength: 10, maxLength: 10 },
  MY: { minLength: 10, maxLength: 11 },
  MZ: { minLength: 9, maxLength: 9 },
  NA: { minLength: 10, maxLength: 10 },
  NC: { minLength: 6, maxLength: 6 },
  NE: { minLength: 8, maxLength: 8 },
  NF: { minLength: 10, maxLength: 10 },
  NG: { minLength: 10, maxLength: 11 },
  NI: { minLength: 8, maxLength: 8 },
  NL: { minLength: 9, maxLength: 9 },
  NO: { minLength: 8, maxLength: 8 },
  NP: { minLength: 10, maxLength: 10 },
  NR: { minLength: 7, maxLength: 7 },
  NU: { minLength: 5, maxLength: 5 },
  NZ: { minLength: 8, maxLength: 9 },
  OM: { minLength: 8, maxLength: 8 },
  PA: { minLength: 8, maxLength: 8 },
  PE: { minLength: 9, maxLength: 9 },
  PF: { minLength: 6, maxLength: 6 },
  PG: { minLength: 8, maxLength: 8 },
  PH: { minLength: 10, maxLength: 10 },
  PK: { minLength: 10, maxLength: 10 },
  PL: { minLength: 9, maxLength: 9 },
  PM: { minLength: 10, maxLength: 10 },
  PR: { minLength: 10, maxLength: 10 },
  PS: { minLength: 9, maxLength: 9 },
  PT: { minLength: 9, maxLength: 9 },
  PW: { minLength: 7, maxLength: 7 },
  PY: { minLength: 9, maxLength: 10 },
  QA: { minLength: 8, maxLength: 8 },
  RE: { minLength: 10, maxLength: 10 },
  RO: { minLength: 9, maxLength: 9 },
  RS: { minLength: 9, maxLength: 9 },
  RU: { minLength: 10, maxLength: 10 },
  RW: { minLength: 9, maxLength: 9 },
  SA: { minLength: 9, maxLength: 9 },
  SB: { minLength: 5, maxLength: 5 },
  SC: { minLength: 6, maxLength: 6 },
  SD: { minLength: 9, maxLength: 9 },
  SE: { minLength: 7, maxLength: 15 },
  SG: { minLength: 8, maxLength: 8 },
  SH: { minLength: 4, maxLength: 4 },
  SI: { minLength: 8, maxLength: 9 },
  SJ: { minLength: 8, maxLength: 8 },
  SK: { minLength: 9, maxLength: 9 },
  SL: { minLength: 8, maxLength: 8 },
  SM: { minLength: 10, maxLength: 10 },
  SN: { minLength: 9, maxLength: 9 },
  SO: { minLength: 8, maxLength: 8 },
  SR: { minLength: 8, maxLength: 8 },
  SS: { minLength: 7, maxLength: 7 },
  ST: { minLength: 7, maxLength: 7 },
  SV: { minLength: 8, maxLength: 8 },
  SX: { minLength: 10, maxLength: 10 },
  SY: { minLength: 9, maxLength: 9 },
  SZ: { minLength: 8, maxLength: 8 },
  TA: { minLength: 4, maxLength: 4 },
  TC: { minLength: 10, maxLength: 10 },
  TD: { minLength: 8, maxLength: 8 },
  TG: { minLength: 8, maxLength: 8 },
  TH: { minLength: 9, maxLength: 9 },
  TJ: { minLength: 9, maxLength: 9 },
  TK: { minLength: 4, maxLength: 4 },
  TL: { minLength: 8, maxLength: 8 },
  TM: { minLength: 8, maxLength: 8 },
  TN: { minLength: 8, maxLength: 8 },
  TO: { minLength: 7, maxLength: 7 },
  TR: { minLength: 10, maxLength: 10 },
  TT: { minLength: 7, maxLength: 7 },
  TV: { minLength: 4, maxLength: 4 },
  TW: { minLength: 9, maxLength: 9 },
  TZ: { minLength: 9, maxLength: 9 },
  UA: { minLength: 9, maxLength: 9 },
  UG: { minLength: 9, maxLength: 9 },
  UY: { minLength: 8, maxLength: 8 },
  UZ: { minLength: 9, maxLength: 9 },
  VA: { minLength: 10, maxLength: 10 },
  VC: { minLength: 7, maxLength: 7 },
  VE: { minLength: 10, maxLength: 10 },
  VG: { minLength: 7, maxLength: 7 },
  VI: { minLength: 10, maxLength: 10 },
  VN: { minLength: 10, maxLength: 10 },
  VU: { minLength: 7, maxLength: 7 },
  WF: { minLength: 6, maxLength: 6 },
  WS: { minLength: 5, maxLength: 5 },
  XK: { minLength: 8, maxLength: 8 },
  YE: { minLength: 9, maxLength: 9 },
  YT: { minLength: 10, maxLength: 10 },
  ZA: { minLength: 9, maxLength: 9 },
  ZM: { minLength: 9, maxLength: 9 },
  ZW: { minLength: 9, maxLength: 9 },
};

// Default rule for countries not in the map
const defaultRule: CountryPhoneRule = { minLength: 4, maxLength: 15 };

// Function to validate a phone number for a specific country
export function validatePhoneNumber(
  phoneNumber: string,
  countryCode: Country,
): { isValid: boolean; errorMessage?: string } {
  // Remove the country code prefix and any non-digit characters to count only the digits
  const numberWithoutCountryCode = phoneNumber
    .replace(/^\+\d+\s+/, "")
    .replace(/\D/g, "");

  // Get validation rules for the country, or use default rules
  const rules = phoneValidationRules[countryCode] || defaultRule;

  // Check if phone number meets the country-specific requirements
  if (
    rules.exactLength &&
    numberWithoutCountryCode.length !== rules.exactLength
  ) {
    return {
      isValid: false,
      errorMessage: `Phone number must be exactly ${rules.exactLength} digits for this country`,
    };
  }

  if (numberWithoutCountryCode.length < rules.minLength) {
    return {
      isValid: false,
      errorMessage: `Phone number must be at least ${rules.minLength} digits`,
    };
  }

  if (numberWithoutCountryCode.length > rules.maxLength) {
    return {
      isValid: false,
      errorMessage: `Phone number cannot exceed ${rules.maxLength} digits`,
    };
  }

  // Check pattern if specified
  if (rules.pattern && !rules.pattern.test(numberWithoutCountryCode)) {
    return {
      isValid: false,
      errorMessage: "Phone number format is invalid for this country",
    };
  }

  return { isValid: true };
}
